; MIKETA 39F
; This version has delayed 3rd, 4th and 5th notes.

F::
SendInput {F Down}
Sleep 100
SendInput {F Up}
;
Sleep 2260
; 1st
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
;
Sleep 190
; 2nd
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
;
Sleep 343
; 3rd
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
;
Sleep 348
; 4th
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
;
Sleep 200
; 5th
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
