; MIKETA 39F

F::
SendInput {F Down}
Sleep 100
SendInput {F Up}
;
Sleep 2260
; 1st
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
;
Sleep 190
; 2nd ((2nd - 1st) - 10ms) = 300 - 10
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
;
Sleep 323
; 3rd ((3rd - 2nd) - 27 = 450 - 27
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
;
Sleep 340
; 4th ((4th - 3rd) - 10 = 450 - 10
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
;
Sleep 190
; 5th ((5th - 4th) - 10 = 300 - 10
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
