; 9F NASHIYOGUSHI

F::
SendInput {F Down}
Sleep 100
SendInput {F Up}
;
Sleep 6760
; 1st
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
;
Sleep 890
; 2nd
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
;
Sleep 1390
; 3rd
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
;
Sleep 1390
; 4th
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
;
Sleep 890
; 5th
SendInput {Enter Down}
Sleep 100
SendInput {Enter Up}
